name: Rails CI

on:
  push: # Run tests on every push
    branches: 
      - '*' # Matches all branch names
  pull_request: # Run tests on all pull requests
    branches: 
      - '*' # Matches all branch names

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.1-slim
    
    services:
      chrome:
        image: seleniarm/standalone-chromium:latest
        options: >-
          --shm-size=2g
          -e SE_NODE_MAX_SESSIONS=1
          -e SE_NODE_OVERRIDE_MAX_SESSIONS=true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            git \
            build-essential \
            libpq-dev \
            default-libmysqlclient-dev \
            pkg-config \
            nodejs \
            npm

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          CAPYBARA_SERVER_PORT: 3000
          SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
        run: bundle exec rspec .